version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      YOUTUBE_USERNAME: ${YOUTUBE_USERNAME}
      YOUTUBE_PASSWORD: ${YOUTUBE_PASSWORD}
